from pathlib import Path

# Define directory for test emails
test_email_dir = Path("test_emails")
test_email_dir.mkdir(exist_ok=True)

emails = {
    "01_contact_center_complaint.txt": """Subject: Urgent: Internet not working since 2 days
From: customer123@provider.com
Date: Mon, 4 Aug 2025 14:25:00 +0000

Hello Support,

I've been facing internet outage for the past two days at my home. I’ve raised a complaint via your app but haven’t received any response yet.

Please fix this immediately as I’m working from home and this has disrupted my schedule.

Customer ID: 789456123

Regards,
Arjun""",

    "02_hr_policy_update.txt": """Subject: Updated Work From Home Policy - Effective Immediately
From: hr@company.com
Date: Mon, 4 Aug 2025 09:00:00 +0000

Dear Team,

Starting this month, employees will be allowed to work from home up to 3 days a week. Please coordinate with your reporting managers for weekly planning.

This change is made to improve flexibility and work-life balance.

Regards,
HR Team""",

    "03_finance_invoice_reminder.txt": """Subject: Pending Invoice Reminder - INV/2025/0198
From: billing@vendor.com
Date: Sun, 3 Aug 2025 11:45:00 +0000

Dear Customer,

This is a gentle reminder that invoice INV/2025/0198 amounting to ₹75,000 is still unpaid. Kindly settle the dues by August 7th to avoid late fees.

Regards,
Finance Department
ABC Services Pvt Ltd""",

    "04_sales_lead_inquiry.txt": """Subject: Looking for pricing details for your enterprise plan
From: prospective.client@company.org
Date: Tue, 5 Aug 2025 17:30:00 +0000

Hello Sales Team,

I came across your AI solutions and am particularly interested in your enterprise plan. Could you please send me the pricing details, deployment options, and if there's a demo available?

Thanks & Regards,
Ananya
IT Manager, Zyntec Corp""",

    "05_devops_alert_log.txt": """Subject: Disk usage alert on server-prod-7
From: alerts@monitoring.internal
Date: Tue, 5 Aug 2025 01:20:00 +0000

ALERT: Disk usage on /var partition on server-prod-7 has exceeded 90%.

Recommended Action:
- Clean up logs older than 7 days
- Verify if backup snapshots are accumulating

This message was auto-generated by the infrastructure monitoring system.
"""
}

# Write files
for filename, content in emails.items():
    with open(test_email_dir / filename, "w") as f:
        f.write(content)

print(f"Created {len(emails)} sample email files in '{test_email_dir.resolve()}'")
